### ISSUE TITLE
Bug in ReefwingAHRS::madgwickUpdate function

### ISSUE THREAD

**Issue by martinbudden** [Reefwing-Software/Reefwing-AHRS#13]
There's a bug in your implementation of the Madgwick update function at
https://github.com/Reefwing-Software/Reefwing-AHRS/blob/main/src/ReefwingAHRS.cpp#L570-L573

It seems like this is an inherited bug that is present in many implementations.

Mark Uckermann has done a thorough investigation at https://github.com/RideBeeline/madgwick-investigation/tree/main?tab=readme-ov-file#madgwicks-filter-implementation-analysis

Essentially the calculation of `bx` and `bz` is out by a factor of two.

The fix is at https://github.com/RideBeeline/madgwick-investigation/blob/main/bug_description.md#bug-2-in-the-c-version-2-missing

**Comment by reefwing** [comment]
Hi @martinbudden - thanks for letting me know. I'll check it out and push through a fix.

**Comment by reefwing** [comment]
Fixed in version 2.3.1

**Comment by martinbudden** [comment]
Glad to be of assistance.
